service: api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

  stage: dev
  region: us-east-1

  environment:
    DYNAMODB_USERS: ${ssm:${self:custom.stage}-dynamodb-users-table}

custom:
  stage: ${opt:stage, self:provider.stage}
  memorySize:
    dev: 128
    prod: 2048

functions:
  register:
    memorySize: ${self:custom.memorySize.${self:custom.stage}}
    role: ${ssm:${self:custom.stage}-register-iam-role}
    handler: register/handler.register
    events:
      - http:
          path: /users
          method: post
